# Generated by Django 4.1.7 on 2023-02-26 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.PositiveIntegerField()),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('enderecos', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('AP', 'Amapá'), ('ES', 'Espirito Santo'), ('SE', 'Sergipe'), ('BA', 'Bahia'), ('PR', 'Paraná'), ('AC', 'Acre'), ('DF', 'Distrito Federal'), ('MS', 'Mato Grosso do Sul'), ('SC', 'Santa Catarina'), ('MT', 'Mato Grosso'), ('TO', 'Tocantins'), ('RJ', 'Rio de Janeiro'), ('PA', 'Pará'), ('MG', 'Minas Gerais'), ('PI', 'Piauí'), ('RO', 'Rondônia'), ('PE', 'Pernambuco'), ('RN', 'Rio Grande do Norte'), ('GO', 'Goiás'), ('AM', 'amazonas'), ('CE', 'Ceará'), ('SP', 'São Paulo'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('PB', 'Praíba'), ('AL', 'Alagoas'), ('MA', 'Maranhão')], default='SP', max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
