# Generated by Django 4.1.7 on 2023-03-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pernambuco'), ('PR', 'Paraná'), ('MG', 'Minas Gerais'), ('RO', 'Rondônia'), ('RS', 'Rio Grande do Sul'), ('DF', 'Distrito Federal'), ('MT', 'Mato Grosso'), ('RR', 'Roraima'), ('PA', 'Pará'), ('BA', 'Bahia'), ('AM', 'amazonas'), ('CE', 'Ceará'), ('RJ', 'Rio de Janeiro'), ('SC', 'Santa Catarina'), ('RN', 'Rio Grande do Norte'), ('GO', 'Goiás'), ('AP', 'Amapá'), ('MA', 'Maranhão'), ('PI', 'Piauí'), ('TO', 'Tocantins'), ('PB', 'Praíba'), ('SP', 'São Paulo'), ('AL', 'Alagoas'), ('ES', 'Espirito Santo'), ('MS', 'Mato Grosso do Sul'), ('SE', 'Sergipe'), ('AC', 'Acre')], default='SP', max_length=2),
        ),
    ]
