# Generated by Django 4.1.7 on 2023-03-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_alter_perfil_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('RO', 'Rondônia'), ('SE', 'Sergipe'), ('CE', 'Ceará'), ('AC', 'Acre'), ('TO', 'Tocantins'), ('RJ', 'Rio de Janeiro'), ('RS', 'Rio Grande do Sul'), ('MT', 'Mato Grosso'), ('GO', 'Goiás'), ('RR', 'Roraima'), ('AL', 'Alagoas'), ('PE', 'Pernambuco'), ('AP', 'Amapá'), ('AM', 'amazonas'), ('SC', 'Santa Catarina'), ('PR', 'Paraná'), ('DF', 'Distrito Federal'), ('PA', 'Pará'), ('ES', 'Espirito Santo'), ('MG', 'Minas Gerais'), ('PB', 'Praíba'), ('PI', 'Piauí'), ('MS', 'Mato Grosso do Sul'), ('SP', 'São Paulo'), ('MA', 'Maranhão'), ('RN', 'Rio Grande do Norte'), ('BA', 'Bahia')], default='SP', max_length=2),
        ),
    ]
