# Generated by Django 4.1.7 on 2023-03-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_perfil_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('BA', 'Bahia'), ('DF', 'Distrito Federal'), ('GO', 'Goiás'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('RR', 'Roraima'), ('AM', 'amazonas'), ('RS', 'Rio Grande do Sul'), ('AL', 'Alagoas'), ('AC', 'Acre'), ('PR', 'Paraná'), ('MG', 'Minas Gerais'), ('RO', 'Rondônia'), ('CE', 'Ceará'), ('AP', 'Amapá'), ('MT', 'Mato Grosso'), ('RN', 'Rio Grande do Norte'), ('PE', 'Pernambuco'), ('TO', 'Tocantins'), ('ES', 'Espirito Santo'), ('SC', 'Santa Catarina'), ('MA', 'Maranhão'), ('PI', 'Piauí'), ('SE', 'Sergipe'), ('PB', 'Praíba'), ('MS', 'Mato Grosso do Sul'), ('PA', 'Pará')], default='SP', max_length=2),
        ),
    ]
