# Generated by Django 4.1.7 on 2023-03-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_alter_perfil_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('AM', 'amazonas'), ('AL', 'Alagoas'), ('AC', 'Acre'), ('RO', 'Rondônia'), ('RJ', 'Rio de Janeiro'), ('PE', 'Pernambuco'), ('TO', 'Tocantins'), ('SC', 'Santa Catarina'), ('GO', 'Goiás'), ('CE', 'Ceará'), ('PR', 'Paraná'), ('BA', 'Bahia'), ('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('DF', 'Distrito Federal'), ('RR', 'Roraima'), ('PI', 'Piauí'), ('ES', 'Espirito Santo'), ('MS', 'Mato Grosso do Sul'), ('MA', 'Maranhão'), ('PA', 'Pará'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('SE', 'Sergipe'), ('PB', 'Praíba'), ('AP', 'Amapá'), ('MT', 'Mato Grosso')], default='SP', max_length=2),
        ),
    ]
