# Generated by Django 4.1.7 on 2023-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_alter_perfil_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('SE', 'Sergipe'), ('SC', 'Santa Catarina'), ('RO', 'Rondônia'), ('RN', 'Rio Grande do Norte'), ('MA', 'Maranhão'), ('RR', 'Roraima'), ('AC', 'Acre'), ('SP', 'São Paulo'), ('AP', 'Amapá'), ('CE', 'Ceará'), ('GO', 'Goiás'), ('MS', 'Mato Grosso do Sul'), ('PI', 'Piauí'), ('AL', 'Alagoas'), ('BA', 'Bahia'), ('ES', 'Espirito Santo'), ('RS', 'Rio Grande do Sul'), ('DF', 'Distrito Federal'), ('PA', 'Pará'), ('PE', 'Pernambuco'), ('MG', 'Minas Gerais'), ('TO', 'Tocantins'), ('RJ', 'Rio de Janeiro'), ('AM', 'amazonas'), ('MT', 'Mato Grosso'), ('PB', 'Praíba'), ('PR', 'Paraná')], default='SP', max_length=2),
        ),
    ]
