# Generated by Django 4.1.7 on 2023-03-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_imagem_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variacao',
        ),
    ]
