# Generated by Django 4.1.7 on 2023-03-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='preço promo'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='preco_promocional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='preço promo'),
        ),
    ]
