# Generated by Django 4.1.7 on 2023-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('C', 'Criado'), ('R', 'Reprovado'), ('F', 'Finalizado'), ('E', 'Enviado'), ('A', 'Aprovado'), ('P', 'Pendente')], default='C', max_length=1),
        ),
    ]
