# Generated by Django 4.1.7 on 2023-02-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('F', 'Finalizado'), ('E', 'Enviado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('C', 'Criado')], default='C', max_length=1),
        ),
    ]
