# Generated by Django 4.1.7 on 2023-02-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Enviado'), ('A', 'Aprovado'), ('F', 'Finalizado'), ('C', 'Criado'), ('R', 'Reprovado')], default='C', max_length=1),
        ),
    ]
