# Generated by Django 4.1.7 on 2023-03-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('C', 'Criado'), ('E', 'Enviado'), ('P', 'Pendente'), ('F', 'Finalizado')], default='C', max_length=1),
        ),
    ]
