# Generated by Django 4.1.7 on 2023-03-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('E', 'Enviado'), ('R', 'Reprovado'), ('C', 'Criado'), ('F', 'Finalizado'), ('P', 'Pendente')], default='C', max_length=1),
        ),
    ]
