# Generated by Django 4.1.7 on 2023-03-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_alter_itempedido_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco_promocional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('R', 'Reprovado'), ('F', 'Finalizado'), ('P', 'Pendente'), ('A', 'Aprovado'), ('E', 'Enviado'), ('C', 'Criado')], default='C', max_length=1),
        ),
    ]
