# Generated by Django 4.1.7 on 2023-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_alter_itempedido_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco_promocional',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('E', 'Enviado'), ('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Reprovado'), ('C', 'Criado'), ('F', 'Finalizado')], default='C', max_length=1),
        ),
    ]
